# Generated by Django 5.2.11 on 2026-03-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curp', models.CharField(max_length=18, unique=True, verbose_name='CURP')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre(s)')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Género')),
                ('direccion', models.TextField(verbose_name='Dirección Completa')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('tipo_sangre', models.CharField(choices=[('O+', 'O Positivo'), ('O-', 'O Negativo'), ('A+', 'A Positivo'), ('A-', 'A Negativo'), ('B+', 'B Positivo'), ('B-', 'B Negativo'), ('AB+', 'AB Positivo'), ('AB-', 'AB Negativo')], max_length=3, verbose_name='Tipo de Sangre')),
                ('alergias', models.TextField(blank=True, null=True, verbose_name='Alergias')),
                ('es_activo', models.BooleanField(default=True, verbose_name='Estatus Activo')),
            ],
        ),
    ]
