# Generated by Django 5.2.11 on 2026-03-03 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curp', models.CharField(max_length=18, unique=True, verbose_name='CURP')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre(s)')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Género')),
                ('direccion', models.TextField(verbose_name='Dirección Completa')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('tipo_sangre', models.CharField(choices=[('O+', 'O Positivo'), ('O-', 'O Negativo'), ('A+', 'A Positivo'), ('A-', 'A Negativo'), ('B+', 'B Positivo'), ('B-', 'B Negativo'), ('AB+', 'AB Positivo'), ('AB-', 'AB Negativo')], max_length=3, verbose_name='Tipo de Sangre')),
                ('alergias', models.TextField(blank=True, null=True, verbose_name='Alergias')),
                ('es_activo', models.BooleanField(default=True, verbose_name='Estatus Activo')),
            ],
        ),
        migrations.CreateModel(
            name='NotaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de atención')),
                ('tipo_consulta', models.CharField(choices=[('General', 'Medicina General'), ('Especialidad', 'Especialidad'), ('Urgencia', 'Urgencia'), ('Chequeo', 'Chequeo')], max_length=20, verbose_name='Tipo de Consulta')),
                ('motivo_consulta', models.TextField(verbose_name='Motivo de Consulta')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('estatura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Estatura (m)')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura (°C)')),
                ('imc', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='IMC')),
                ('presion_arterial', models.CharField(blank=True, max_length=20, null=True, verbose_name='Presión Arterial')),
                ('ritmo_cardiaco', models.IntegerField(blank=True, null=True, verbose_name='Ritmo Cardíaco (bpm)')),
                ('exploracion_fisica', models.TextField(verbose_name='Exploración Física')),
                ('diagnostico', models.TextField(verbose_name='Diagnóstico')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Doctor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinica.paciente', verbose_name='Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Medicamento')),
                ('dosis', models.CharField(max_length=100, verbose_name='Dosis')),
                ('frecuencia', models.CharField(max_length=100, verbose_name='Frecuencia')),
                ('duracion', models.CharField(max_length=100, verbose_name='Duración')),
                ('indicaciones', models.TextField(blank=True, null=True, verbose_name='Indicaciones adicionales')),
                ('nota_medica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='clinica.notamedica', verbose_name='Nota Médica')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.paciente', verbose_name='Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('COVID-19', 'COVID-19 (Sars-CoV-2)'), ('BCG', 'BCG (Tuberculosis)'), ('Hepatitis B', 'Hepatitis B'), ('Pentavalente', 'Pentavalente acelular'), ('Rotavirus', 'Rotavirus'), ('Neumocócica', 'Neumocócica conjugada'), ('Influenza', 'Influenza'), ('SRP', 'SRP (Sarampión, Rubeola, Parotiditis)'), ('Sabin', 'Sabin (Polio)'), ('DPT', 'DPT (Difteria, Tos ferina, Tétanos)'), ('SR', 'SR (Sarampión y Rubeola)'), ('TD', 'Tétanos y Difteria'), ('VPH', 'VPH (Virus del Papiloma Humano)')], max_length=100, verbose_name='Nombre de la Vacuna')),
                ('dosis', models.CharField(choices=[('Unica', 'Dosis Única'), ('1ra', 'Primera Dosis'), ('2da', 'Segunda Dosis'), ('3ra', 'Tercera Dosis'), ('4ta', 'Cuarta Dosis'), ('Refuerzo', 'Refuerzo'), ('Anual', 'Dosis Anual')], max_length=50, verbose_name='Dosis')),
                ('lote', models.CharField(max_length=50, verbose_name='Número de Lote')),
                ('fecha_aplicacion', models.DateField(verbose_name='Fecha de Aplicación')),
                ('nota_medica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunas', to='clinica.notamedica', verbose_name='Nota Médica')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.paciente', verbose_name='Paciente')),
            ],
        ),
    ]
