# Generated by Django 5.2.11 on 2026-03-01 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de atención')),
                ('tipo_consulta', models.CharField(choices=[('General', 'Medicina General'), ('Especialidad', 'Especialidad'), ('Urgencia', 'Urgencia'), ('Chequeo', 'Chequeo')], max_length=20, verbose_name='Tipo de Consulta')),
                ('motivo_consulta', models.TextField(verbose_name='Motivo de Consulta')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('estatura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Estatura (m)')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura (°C)')),
                ('imc', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='IMC')),
                ('presion_arterial', models.CharField(blank=True, max_length=20, null=True, verbose_name='Presión Arterial')),
                ('ritmo_cardiaco', models.IntegerField(blank=True, null=True, verbose_name='Ritmo Cardíaco (bpm)')),
                ('exploracion_fisica', models.TextField(verbose_name='Exploración Física')),
                ('diagnostico', models.TextField(verbose_name='Diagnóstico')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Doctor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.paciente', verbose_name='Paciente')),
            ],
        ),
    ]
