# Generated by Django 5.2.11 on 2026-03-02 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_notamedica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Medicamento')),
                ('dosis', models.CharField(max_length=100, verbose_name='Dosis (Ej: 500mg)')),
                ('frecuencia', models.CharField(max_length=100, verbose_name='Frecuencia (Ej: Cada 8 horas)')),
                ('duracion', models.CharField(max_length=100, verbose_name='Duración del tratamiento (Ej: 7 días)')),
                ('nota_medica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='clinica.notamedica', verbose_name='Nota Médica')),
            ],
        ),
    ]
