# Generated by Django 5.2.11 on 2026-03-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_medicamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='indicaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Indicaciones adicionales'),
        ),
    ]
